spring:
  application:
    name: users-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/psinder
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8095


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    preferIpAddress: true